// Stub module: web-ifc-three imports 'web-ifc'; we already load the IIFE
// (web-ifc-api-iife.js) which sets window.WebIFC. Re-export that global.
const WebIFC = window.WebIFC;
export default WebIFC;
export const IfcAPI = WebIFC.IfcAPI;
export const IFCSPACE = WebIFC.IFCSPACE;
export const IFCOPENINGELEMENT = WebIFC.IFCOPENINGELEMENT;
export const IFCPRODUCTDEFINITIONSHAPE = WebIFC.IFCPRODUCTDEFINITIONSHAPE;
export const IFCRELAGGREGATES = WebIFC.IFCRELAGGREGATES;
export const IFCRELCONTAINEDINSPATIALSTRUCTURE = WebIFC.IFCRELCONTAINEDINSPATIALSTRUCTURE;
export const IFCRELDEFINESBYPROPERTIES = WebIFC.IFCRELDEFINESBYPROPERTIES;
export const IFCRELASSOCIATESMATERIAL = WebIFC.IFCRELASSOCIATESMATERIAL;
export const IFCRELDEFINESBYTYPE = WebIFC.IFCRELDEFINESBYTYPE;
export const IFCPROJECT = WebIFC.IFCPROJECT;
export const IFCBUILDING = WebIFC.IFCBUILDING;
export const IFCELEMENT = WebIFC.IFCELEMENT;
export const IFCWALL = WebIFC.IFCWALL;
